local GJB = LibStub("AceAddon-3.0"):GetAddon("GarrisonJukeBox")
local L = GJB.L -- local L = LibStub("AceLocale-3.0"):GetLocale("GarrisonJukeBox")

local zones = {
	-- Order Halls
	{L["ZONE_LEGION_ACHERUS"], 1021}, --DK
	{L["ZONE_LEGION_SKYHOLD"], 1035}, --Warrior
	{L["ZONE_LEGION_HALLOFTHEGUARDIAN"], 1068}, --Mage
	{L["ZONE_LEGION_MARDUM"], 1052}, --DH
	{L["ZONE_LEGION_NETHERLIGHTTEMPLE"], 1040}, --Priest
	{L["ZONE_LEGION_THEDREAMGROVE"], 1077}, --Druid
	{L["ZONE_LEGION_HEARTOFAZEROTH"], 1057}, --Shaman
	{L["ZONE_LEGION_WANDERINGISLE"], 1044}, --Monk
	{L["ZONE_LEGION_TRUESHOTLODGE"], 1072}, --Hunter

	-- Zones
	{L["ZONE_LEGION_BROKENISLES"], 1007},
	{L["ZONE_LEGION_AZSUNA"], 1015},
	{L["ZONE_LEGION_BROKENSHORE"], 1021},
	{L["ZONE_LEGION_DALARAN"], 1014},
	{L["ZONE_LEGION_EYEOFAZSHARA"], 1096},
	{L["ZONE_LEGION_HIGHMOUNTAIN"], 1024},
	{L["ZONE_LEGION_STORMHEIM"], 1017},
	{L["ZONE_LEGION_SURAMAR"], 1033},
	{L["ZONE_LEGION_VALSHARA"], 1018},

	-- Argus
	{L["ZONE_LEGION_KROKUUN"], 1135},
	{L["ZONE_LEGION_MACAREE"], 1170},
	{L["ZONE_LEGION_ANTORANWASTES"], 1171},
	{L["ZONE_LEGION_ARGUS"], 1184},
}

GJB.zonetable[GJB.ZONE_LEGION] = zones