local GJB = LibStub("AceAddon-3.0"):GetAddon("GarrisonJukeBox")
local L = GJB.L -- local L = LibStub("AceLocale-3.0"):GetLocale("GarrisonJukeBox")

local zones = {
	{L["ZONE_DUNGEON_Blackfathom Deeps"], 688},
	{L["ZONE_DUNGEON_Blackrock Depths"], 704},
	{L["ZONE_DUNGEON_Blackrock Spire"], 721},
	{L["ZONE_DUNGEON_Dire Maul"], 699},
	{L["ZONE_DUNGEON_Gnomeregan"], 691},
	{L["ZONE_DUNGEON_Maraudon"], 750},
	{L["ZONE_DUNGEON_Ragefire Chasm"], 680},
	{L["ZONE_DUNGEON_Razorfen Downs"], 760},
	{L["ZONE_DUNGEON_Razorfen Kraul"], 761},
	{L["ZONE_DUNGEON_Shadowfang Keep"], 764},
	{L["ZONE_DUNGEON_Stratholme"], 765},
	{L["ZONE_DUNGEON_The Deadmines"], 756},
	{L["ZONE_DUNGEON_The Stockade"], 690},
	{L["ZONE_DUNGEON_The Temple of Atal'Hakkar"], 687},
	{L["ZONE_DUNGEON_Uldaman"], 692},
	{L["ZONE_DUNGEON_Wailing Caverns"], 749},
	{L["ZONE_DUNGEON_Zul'Farrak"], 686},
	{L["ZONE_DUNGEON_Auchenai Crypts"], 722},
	{L["ZONE_DUNGEON_Hellfire Ramparts"], 797},
	{L["ZONE_DUNGEON_Magisters' Terrace"], 798},
	{L["ZONE_DUNGEON_Mana-Tombs"], 732},
	{L["ZONE_DUNGEON_Old Hillsbrad Foothills"], 734},
	{L["ZONE_DUNGEON_Sethekk Halls"], 723},
	{L["ZONE_DUNGEON_Shadow Labyrinth"], 724},
	{L["ZONE_DUNGEON_The Arcatraz"], 731},
	{L["ZONE_DUNGEON_The Black Morass"], 733},
	{L["ZONE_DUNGEON_The Blood Furnace"], 725},
	{L["ZONE_DUNGEON_The Botanica"], 729},
	{L["ZONE_DUNGEON_The Mechanar"], 730},
	{L["ZONE_DUNGEON_The Shattered Halls"], 710},
	{L["ZONE_DUNGEON_The Slave Pens"], 728},
	{L["ZONE_DUNGEON_The Steamvault"], 727},
	{L["ZONE_DUNGEON_The Underbog"], 726},
	{L["ZONE_DUNGEON_Ahn'kahet: The Old Kingdom"], 522},
	{L["ZONE_DUNGEON_Azjol-Nerub"], 533},
	{L["ZONE_DUNGEON_Drak'Tharon Keep"], 534},
	{L["ZONE_DUNGEON_Gundrak"], 530},
	{L["ZONE_DUNGEON_Halls of Lightning"], 525},
	{L["ZONE_DUNGEON_Halls of Reflection"], 603},
	{L["ZONE_DUNGEON_Halls of Stone"], 526},
	{L["ZONE_DUNGEON_Pit of Saron"], 602},
	{L["ZONE_DUNGEON_The Culling of Stratholme"], 521},
	{L["ZONE_DUNGEON_The Forge of Souls"], 601},
	{L["ZONE_DUNGEON_The Nexus"], 520},
	{L["ZONE_DUNGEON_The Oculus"], 528},
	{L["ZONE_DUNGEON_The Violet Hold"], 536},
	{L["ZONE_DUNGEON_Trial of the Champion"], 542},
	{L["ZONE_DUNGEON_Utgarde Keep"], 523},
	{L["ZONE_DUNGEON_Utgarde Pinnacle"], 524},
	{L["ZONE_DUNGEON_Blackrock Caverns"], 753},
	{L["ZONE_DUNGEON_End Time"], 820},
	{L["ZONE_DUNGEON_Grim Batol"], 757},
	{L["ZONE_DUNGEON_Halls of Origination"], 759},
	{L["ZONE_DUNGEON_Hour of Twilight"], 819},
	{L["ZONE_DUNGEON_Lost City of the Tol'vir"], 747},
	{L["ZONE_DUNGEON_The Stonecore"], 768},
	{L["ZONE_DUNGEON_The Vortex Pinnacle"], 769},
	{L["ZONE_DUNGEON_Throne of the Tides"], 767},
	{L["ZONE_DUNGEON_Well of Eternity"], 816},
	{L["ZONE_DUNGEON_Zul'Aman"], 781},
	{L["ZONE_DUNGEON_Zul'Gurub"], 793},
	{L["ZONE_DUNGEON_Gate of the Setting Sun"], 875},
	{L["ZONE_DUNGEON_Mogu'Shan Palace"], 885},
	{L["ZONE_DUNGEON_Scarlet Halls"], 871},
	{L["ZONE_DUNGEON_Scarlet Monastery"], 874},
	{L["ZONE_DUNGEON_Scholomance"], 898},
	{L["ZONE_DUNGEON_Shado-pan Monastery"], 877},
	{L["ZONE_DUNGEON_Siege of Niuzao Temple"], 887},
	{L["ZONE_DUNGEON_Stormstout Brewery"], 876},
	{L["ZONE_DUNGEON_Temple of the Jade Serpent"], 867},
	{L["ZONE_DUNGEON_Auchindoun"], 984},
	{L["ZONE_DUNGEON_Bloodmaul Slag Mines"], 964},
	{L["ZONE_DUNGEON_Grimrail Depot"], 993},
	{L["ZONE_DUNGEON_Iron Docks"], 987},
	{L["ZONE_DUNGEON_Shadowmoon Burial Grounds"], 969},
	{L["ZONE_DUNGEON_Skyreach"], 989},
	{L["ZONE_DUNGEON_The Everbloom"], 1008},
	{L["ZONE_DUNGEON_Upper Blackrock Spire"], 995},
	{L["ZONE_DUNGEON_Black Rook Hold"], 1081},
	{L["ZONE_DUNGEON_Cathedral of Eternal Night"], 1146},
	{L["ZONE_DUNGEON_Court of Stars"], 1087},
	{L["ZONE_DUNGEON_Darkheart Thicket"], 1067},
	{L["ZONE_DUNGEON_Eye of Azshara"], 1046},
	{L["ZONE_DUNGEON_Halls of Valor"], 1041},
	{L["ZONE_DUNGEON_Maw of Souls"], 1042},
	{L["ZONE_DUNGEON_Neltharion's Lair"], 1065},
	{L["ZONE_DUNGEON_Return to Karazhan"], 1115},
	{L["ZONE_DUNGEON_The Arcway"], 1079},
	{L["ZONE_DUNGEON_Vault of the Wardens"], 1045},
	{L["ZONE_DUNGEON_Violet Hold"], 1066},
}

GJB.zonetable[GJB.ZONE_DUNGEONS] = zones